services:
  amq:
    container_name: amq
    build: docker/amq
    image: amq
    ports:
      - 8161:8161
      - 61616:61616
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
